=== ajkaran738/SDL/xml/employees.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="company">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="employee" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:string"/>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="first" type="xs:string"/>
                    <xs:element name="last" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="department" type="xs:string"/>
              <xs:element name="salary" type="xs:decimal"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ajkaran738/SDL/xml/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employees.xsd">
  <!--XML document that you want to validate against the schema. -->
  <employee>
    <id>E001</id>
    <name>
      <first>John</first>
      <last>Doe</last>
    </name>
    <department>IT</department>
    <salary>75000.00</salary>
  </employee>
  <employee>
    <id>E002</id>
    <name>
      <first>Jane</first>
      <last>Smith</last>
    </name>
    <department>HR</department>
    <salary>12345</salary>
  </employee>
</company>
